---
version: "3"
# https://docs.docker.com/compose/compose-file/compose-file-v3/#deploy
services:

  embark_db:
    container_name: embark_db
    image: mysql:latest
    labels:
      flag: "EMBArk_server_mysql_container"
    env_file:
      - .env
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    expose:
      - "3306"
    restart: always
    volumes:
      - ./mysql.cnf:/etc/my.cnf
      - ./mysql-init:/docker-entrypoint-initdb.d
      - ./embark_db:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      embark_backend:
        ipv4_address: "172.22.0.5"
    logging:
      driver: "local"

  embark_redis:
    container_name: embark_redis
    image: "redis:5"
    labels:
      flag: "EMBArk_server_redis_container"
    env_file:
      - .env
    command: --port 7777
    expose:
      - "7777"
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      embark_backend:
        ipv4_address: "172.22.0.8"
    logging:
      driver: "local"


networks:
  embark_backend:
    name: embark_backend
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: embark_backend
    ipam:
      config:
        - subnet: "172.22.0.0/16"
