openapi: 3.1.1
info:
  title: EMBArk API
  description: API of the firmware security scanning environment
  version: "0.2"
  license:
    name: "MIT License"
    identifier: "MIT"
  contact:
    name: EMBA - The security analyzer for firmware of embedded devices
    url: https://github.com/e-m-b-a

paths: {}
