name: EMBArk Django tests

on: [push]

jobs:
  run-django-tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Install python libs
      #  run: |
      #    sudo apt-get update
      #    sudo apt-get install -y python3-dev
      #    sudo pip install --upgrade pipenv

      - name: Restore cached Docker images
        id: docker-cache-restore
        uses: actions/cache@v3
        with:
          path: docker-cache/db-images.tar
          key: embark-db-images-v1

      - name: Load Docker image from cache
        if: steps.docker-cache-restore.outputs.cache-hit == 'true'
        run: |
          docker load -i docker-cache/db-images.tar

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Set env for .venv in project
        run: echo "PIPENV_VENV_IN_PROJECT=1" >> $GITHUB_ENV

      - name: Install Pipenv
        run: pip install --upgrade pipenv

      - name: Restore Pipenv cache
        id: pipenv-cache
        uses: actions/cache@v3
        with:
          path: .venv
          key: pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        run: pipenv install --deploy --ignore-pipfile

      - name: EMBArk default install
        run: ./installer.sh -sF

      - name: Save Docker images to cache
        if: steps.docker-cache-restore.outputs.cache-hit != 'true'
        run: |
          mkdir -p docker-cache
          docker save mysql:latest redis:5 -o docker-cache/db-images.tar

      - name: Start DB
        run: |
          docker compose up -d
          cd embark
          pipenv run python manage.py makemigrations users uploader reporter dashboard porter workers
          pipenv run python manage.py migrate

      - name: Run tests
        run: |
          cd embark
          pipenv run python manage.py test
