# This workflow will run build EMBArk in dev-mode

name: Build-EMBArk-DEV-test

on: [push]

jobs:
  Build-embark:
    if: github.repository_owner != 'e-m-b-a'
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          swap-storage: true

      - name: Restore cached Docker image
        id: docker-cache-restore
        uses: actions/cache@v3
        with:
          path: docker-cache/emba-image.tar
          key: emba-docker-image-v1

      - name: Load Docker image from cache
        if: steps.docker-cache-restore.outputs.cache-hit == 'true'
        run: |
          docker load -i docker-cache/emba-image.tar

      - name: EMBArk dev install
        uses: Wandalen/wretry.action@master
        with:
          command: sudo ./installer.sh -sF
          attempt_limit: 3

      - name: Save Docker image to cache
        if: steps.docker-cache-restore.outputs.cache-hit != 'true'
        run: |
          mkdir -p docker-cache
          docker tag embeddedanalyzer/emba:1.5.2c embeddedanalyzer/emba:latest || true
          docker save embeddedanalyzer/emba:latest -o docker-cache/emba-image.tar

      # - name: Start Debug-server-conf
      #   run: |
      #      sudo ./dev-tools/debug-server-start.sh &
      #      sleep 5m
      #      echo "Let the user test"
      #   timeout-minutes: 10
