# This workflow tests the project for proper linting

name: Lint and check all

on:
  push:
    branches:
      - '**'        # matches every branch
  pull_request:
    branches:
      - '**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v4
    - name: Install dependencies for linting
      run: |
        sudo apt-get update -y
        sudo apt-get install -y python3-dev npm pycodestyle bandit pylint
        sudo npm install -g jshint
        sudo npm install -g @stoplight/spectral-cli
    - name: Install Python, pipenv and Pipfile packages
      uses: palewire/install-python-pipenv-pipfile@v4
      with:
        python-version: '3.10'
    - name: Make dirs
      run: |
        mkdir ./embark/logs
        touch ./embark/logs/web.log
        mkdir ./embark/uploadFirmwareImages
    - name: Run checkproject
      run: |
        pipenv install --dev
        ./dev-tools/check_project.sh
      env:
        PIPENV_VENV_IN_PROJECT: "True"
        DJANGO_SECRET_KEY: $(python3 -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())')
        DATABASE_NAME: "embark"
        DATABASE_USER: "embark"
        DATABASE_PASSWORD: "embark"
        DATABASE_HOST: "127.0.0.1"
        DATABASE_PORT: "3306"
        MYSQL_PASSWORD: "embark"
        MYSQL_USER: "embark"
        MYSQL_DATABASE: "embark"
        REDIS_HOST: "127.0.0.1"
        REDIS_PORT: "7777"
        SECRET_KEY: "$DJANGO_SECRET_KEY"
        HASHID_SALT: "EMBArk1234ยง$S@lt"
        DJANGO_SUPERUSER_PASSWORD:  "embark"
        DJANGO_SUPERUSER_USERNAME:  "superuser"
        DJANGO_SUPERUSER_EMAIL:  "idk@lol.com"

